Cuongdd
hiimBugCreator/nha_tui_o_quan_3 pull request #6
Opened 2024-11-24 04:10 UTC by DamDinhCuong

2024-11-24 07:15 UTC, hauletrung requested changes

2024-11-24 07:15 UTC, hauletrung commented on index.html
> +			// buildings, homes, etc. - add your data in data_script/locations.js
remove đoạn này đi @DamDinhCuong

2024-11-25 03:34 UTC, DamDinhCuong commented
e xóa ròi anh ạ

2024-11-25 03:46 UTC, hauletrung approved these changes

2024-11-25 03:46 UTC, merged